### ISSUE TITLE
Build failures with latticefx r643

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mccdo/latticefx#1]
```
latticefx r643 fails to build on RHEL 6, openSUSE 12.1, SLES 11 SP2, and Ubuntu 
12.04 LTS.

What steps will reproduce the problem?
1. Check out latticefx trunk on one of the aforementioned OSes
2. configure with CMake
3. make

What is the expected output? What do you see instead?

I expect a successful build. Instead, I see:

[ 19%] Built target latticefx_utils_vtk
[ 34%] Built target latticefx_translators_vtk
[ 35%] Building CXX object 
src/latticefx/core/CMakeFiles/latticefx_core.dir/ChannelDataOSGArray.cpp.o
/home/buildbot/dev/deps/latticefx/src/latticefx/core/ChannelDataOSGArray.cpp: 
In member function ‘void 
lfx::core::ChannelDataOSGArray::copyArray(osg::Array*, const osg::Array*)’:
/home/buildbot/dev/deps/latticefx/src/latticefx/core/ChannelDataOSGArray.cpp:337
: error: ‘memcpy’ was not declared in this scope
/home/buildbot/dev/deps/latticefx/src/latticefx/core/ChannelDataOSGArray.cpp:343
: error: ‘memcpy’ was not declared in this scope
/home/buildbot/dev/deps/latticefx/src/latticefx/core/ChannelDataOSGArray.cpp:349
: error: ‘memcpy’ was not declared in this scope
/home/buildbot/dev/deps/latticefx/src/latticefx/core/ChannelDataOSGArray.cpp:355
: error: ‘memcpy’ was not declared in this scope
make[2]: *** 
[src/latticefx/core/CMakeFiles/latticefx_core.dir/ChannelDataOSGArray.cpp.o] 
Error 1
make[1]: *** [src/latticefx/core/CMakeFiles/latticefx_core.dir/all] Error 2
make: *** [all] Error 2


The attached patch fixes the build problem.
```

Original issue reported on code.google.com by `karls...@gmail.com` on 5 Mar 2013 at 7:05

Attachments:
- [latticefx-r643-memcpy.patch](https://storage.googleapis.com/google-code-attachments/latticefx/issue-1/comment-0/latticefx-r643-memcpy.patch)
